### ISSUE TITLE
Usage with raw-loader → expose AbstractSyntaxTree?

### ISSUE THREAD

**Issue by mesqueeb** [TheRealSyler/sass-lsp-server#3]
I just wanna say that this package is awesome! Being able to create an `AbstractSyntaxTree` from a SASS file is very cool.

I already use the webpack `raw-loader` a lot in a project of mine, and now I wanna do something with SASS files as well. I'm thinking of using this package's `AbstractSyntaxTree` class.

three questions:

1. If I use `raw-loader` to get the Sass file content as string, I can just pass it to `new AbstractSyntaxTree().parse(sassFileText)` right?
2. If the above is correct: can you expose the `AbstractSyntaxTree` class to the `dist/server.js` main in-point?
3. Can you host `sass-lsp-server` on NPM, so I can consume it? : )

**Comment by TheRealSyler** [comment]
@mesqueeb sorry for the late response, you should not use this because im no longer working on it and its not finished, if you still want to use it, you can copy the `AbstractSyntaxTree` code finish it and publish it yourself.
